#!/usr/bin/bash

# Check if NVIDIA drivers are available
if command -v nvidia-smi > /dev/null 2>&1; then
  exec env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only "$@"
else
  # AMD
  exec env DRI_PRIME=1 "$@"
fi
